csa-old/config/routes.rb
Rails.application.routes.draw do
  resources :users do
  
  get 'search', on: :collection 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
root 'users#index'
end

csa-old/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

csa-old/app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :firstname, :surname, :grad_year, :email
  validates_numericality_of :grad_year,
                            greater_than_or_equal_to: 1970,
                            less_than_or_equal_to: Time.now.year.to_i
  validates_format_of :email,
                      with: /\A([\w\.\-\+]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
                      message: 'Bad email address format'

  def firstname=(value)
    write_attribute :firstname, (value ? value.humanize : nil)
  end

  def surname=(value)
    write_attribute :surname, (value ? value.humanize : nil)
  end

  self.per_page = 8

end

csa-old/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Make is_admin? a helper method available to view templates
  helper_method :is_admin?

  protected

  def is_admin?
    true
  end
end

csa-old/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_current_page, except: [:index]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :show_record_not_found

  # GET /users
  # GET /users.json
  def index
      @users = User.paginate(page: params[:page],
                             per_page: params[:per_page])
                   .order('surname, firstname')
  end

  def search
   @users = User.paginate(page:params[:page], per_page: params[:per_page]).order('surname,firstname')
  render 'index'
  end


  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to(user_url(@user, page: @current_page),
                                  notice: 'Account was successfully created.') }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to(user_url(@user, page: @current_page),
                                  notice: 'Account was successfully updated.') }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url(page: @current_page) }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def set_current_page
    @current_page = params[:page] || 1
  end

  def show_record_not_found(exception)
    respond_to do |format|
      format.html {
        redirect_to(users_url(page: @current_page),
                    notice: 'Account no longer exists.')
      }
      format.json {
        render json: '{Account no longer exists.}',
               status: :unprocessable_entity
      }
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:surname, :firstname, :phone, :grad_year, :jobs, :email)
  end
end

csa-old/app/helpers/application_helper.rb
module ApplicationHelper
end

csa-old/app/helpers/users_helper.rb
module UsersHelper
end

csa-old/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Csa</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>

<div class="header">
  <%= render :partial => 'sessions/login' %>
  <div class="navigation">
    <%= render_navigation %>
  </div>

  <% flash.each do |key, value| %>
        <span class="flash_<%= key %>">
          <span class="flash_message"><%= value %></span>
        </span>
  <% end %>

</div>
<div class="content">
  <%= yield %>
</div>

<div id="footer">
</div>

</body>
</html>

csa-old/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field_tag 'page', @current_page %>

  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.phone_field :phone %>
  </div>
  <div class="field">
    <%= f.label :grad_year %><br>
    <%= f.number_field :grad_year %>
  </div>
  <div class="field">
    <%= f.label :jobs %><br>
    <%= f.check_box :jobs %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

csa-old/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', user_path(@user, page: @current_page) %> |
<%= link_to 'Back', users_path(page: @current_page) %>

csa-old/app/views/users/index.html.erb
<h1>User accounts</h1>

<% if @users.length > 0 %>
    <%= form_tag(search_users_path,
                 method: :get,
                 id: "search") do %>
      <fieldset>
        <%= text_field_tag(:query) %>
        <%= submit_tag("Search") %>
      </fieldset>
    <% end %>
     <table>
      <thead>
      <tr>
        <th>Surname</th>
        <th>First name</th>
        <th>Email</th>
        <th>Grad. year</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
          <tr class="data">
            <td class="surname"><%= user.surname %></td>
            <td class="firstname"><%= user.firstname %></td>
            <td class="email"><%= user.email %></td>
            <td class="grad_year"><%= user.grad_year %></td>
            <td><%= link_to(image_tag('eye.jpg', alt: 'Show',
                                      title: 'Show details', border: '0'),
                            user_path(user, page: @users.current_page))
            %></td>
            <td><%= link_to(image_tag('edit.png', alt: 'Edit',
                                      title: 'Edit item', border: '0'),
                            edit_user_path(user, page: @users.current_page))
            %></td>
            <td><%= link_to(image_tag('destroy.gif', alt: 'Destroy',
                                      title: 'Destroy item', border: '0'),
                            user_path(user, page: @users.current_page),
                            data: {confirm: 'Are you sure?'},
                            method: :delete)
            %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>
<br>
<div class="digg_pagination">
  <div>
    <%= page_entries_info @users %>
  </div>
  <%= will_paginate @users, container: false %>
</div>
<br>

<%= link_to 'New user', new_user_path(page: @users.current_page) %>

csa-old/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path(page: @current_page) %>

csa-old/app/views/users/show.html.erb
<h1>User details</h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>Surname:</strong>
  <%= @user.surname %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Grad year:</strong>
  <%= @user.grad_year %>
</p>

<p>
  <strong>Jobs:</strong>
  <%= @user.jobs %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user, page: @current_page) %> |
<%= link_to 'Back', users_path(page: @current_page) %>