csa/config/routes.rb
Rails.application.routes.draw do
  resources :users do
    get 'search', on: :collection
  end
  
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
 
  resources :broadcasts, except: [:edit, :update]
  
  # A singleton resource and so no paths requiring ids are generated
  # Also, don't want to support editing of the session
  resource :session, only: [:new, :create, :destroy]
  
  get 'home', to: 'home#index', as: :home
 
  # Will support the following styles of URL:
  # /api/users.json
  # /api/users/1.json
  # /api/users
  namespace :api, defaults: {format: :json} do
    resources :users, except: [:new, :edit]
  end
 
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

csa/app/models/broadcast.rb
class Broadcast < ApplicationRecord

  # The only restriction is that broadcasts must have some data to
  # be valid and an associated broadcaster (user_id)
  validates_presence_of :content

  belongs_to :user
  has_and_belongs_to_many :feeds

  def to_s
    result = "id: " + id.to_s + " content: " + content
    if user
      result += " user: " + user.id.to_s
    end
    result
  end

  def self.per_page
    8
  end
end

csa/app/controllers/broadcasts_controller.rb
class BroadcastsController < ApplicationController
  
  before_action :set_broadcast, only: [:show, :destroy]
  before_action :set_current_page, except: [:index]
  rescue_from ActiveRecord::RecordNotFound, with: :squelch_record_not_found
  
  # This is an admin specific controller, so enforce access by admin only
  # This is a very simple form of authorisation
  before_action :admin_required

  # Default number of entries per page
  PER_PAGE = 12

  # GET /broadcasts
  # GET /broadcasts.json
  def index
    @broadcasts = Broadcast.paginate(page: params[:page],
                                     per_page: params[:per_page])
                           .order('created_at DESC')
  end

  # GET /broadcasts/1
  # GET /broadcasts/1.json
  def show
  end

  # GET /broadcasts/new
  def new
    @broadcast = Broadcast.new
  end

  # POST /broadcasts
  # POST /broadcasts.json
  def create

    @broadcast = Broadcast.new(broadcast_params)

    # Wire up broadcast with the current user (an administrator)
    # Will be an admin user (see before_action)
    # Note the current_user is a user_detail object so we need
    # to navigate to its user object
    @broadcast.user = current_user.user

    # Doing the next line forces a save automatically. I want to defer this
    # until the "if" statement
    #current_user.user.broadcasts << @broadcast

    no_errors = false
    respond_to do |format|
      if @broadcast.save

        # Only after saving do we try and do the real broadcast. Could have been
        # done using an observer, but I wanted this to be more explicit

        results = BroadcastService.broadcast(@broadcast, params[:feeds])
        if results.length > 0
          # Something went wrong when trying to broadcast to one or more of the
          # feeds.
          @broadcast.errors[:base] << ("#{I18n.t('broadcasts.unable-message')}: #{results.inspect}")
          flash[:error] = I18n.t('broadcasts.saved-but-message')
        else
          flash[:notice] = I18n.t('broadcasts.saved-message')
          no_errors = true
        end
        if no_errors
          format.html { redirect_to(broadcasts_url(page: @current_page)) }
          #format.json { render json: @broadcast, status: :created, location: @broadcast }
	  #ActionCable.server.broadcast 'broadcast_channel', message: format.json { render json: @broadcast, status: :created, location: @broadcast }
	  ActionCable.server.broadcast 'broadcast_channel', message: '<p>' +  @broadcast.to_s + '</p>'
        else
          format.html { render action: 'new' }
          format.json {
            # Either say it partly worked but send back the errors or else send
            # back complete failure indicator (couldn't even save)
            if results
              render json: @broadcast.errors, status: :created, location: @broadcast
            else
              render json: @broadcast.errors, status: :unprocessable_entity
            end
          }
        end
      end
    end
  end

  # DELETE /broadcasts/1
  # DELETE /broadcasts/1.json
  def destroy
    @broadcast.destroy
    respond_to do |format|
      format.html { redirect_to broadcasts_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_broadcast
    @broadcast = Broadcast.find(params[:id])
  end

  def set_current_page
    @current_page = params[:page] || 1
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def broadcast_params
    params.require(:broadcast).permit(:content)
  end

  def squelch_record_not_found(exception)
    respond_to do |format|
      format.html { redirect_to(broadcasts_url(page: current_page)) }
      format.json { head :no_content }
    end
  end
end

csa/app/helpers/broadcasts_helper.rb
module BroadcastsHelper

  def display_feeds(broadcast)
    result = ""
    broadcast.feeds.each_with_index do |feed, i|
      result += h feed.name.humanize
      if i < broadcast.feeds.length-1
        result += ", "
      end
    end
    result
  end
end

csa/app/views/broadcasts/index.html.erb
<h1>Broadcasts</h1>

<% if @broadcasts.length > 0 %>
    <table class="sortable" id="sortabletable">
      <thead>
      <tr>
        <th>Date sent</th>
        <th class="unsortable">Feeds</th>
        <th class="unsortable"/>
        <th class="unsortable"/>
      </tr>
      </thead>

      <tbody>
      <% @broadcasts.each do |broadcast| %>
          <tr>
            <td><%= broadcast.created_at %></td>
            <td>
              <%= display_feeds broadcast %>
            </td>

            <td><%= link_to image_tag('eye.jpg', alt: 'Show',
                                      title: 'Show details', border: '0'),
                            broadcast_path(broadcast, page: @broadcasts.current_page) %></td>
            <td><%= link_to image_tag('destroy.gif', alt: 'Destroy',
                                      title: 'Destroy item', border: '0'),
                            broadcast_path(broadcast, page: @broadcasts.current_page),
                            data: {confirm: 'Are you sure?'},
                            method: :delete %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <br/>
<% end %>
<div class="digg_pagination">
  <div clas="page_info">
    <%= page_entries_info @broadcasts %>
  </div>
  <%= will_paginate @broadcasts, container: false %>
</div>

<br/>

<%= link_to 'New broadcast', new_broadcast_path(page: @broadcasts.current_page) %>

csa/app/views/broadcasts/new.html.erb
<h1>New broadcast</h1>

<%= form_for(@broadcast) do |f| %>
    <% if @broadcast.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@broadcast.errors.count, "error") %> prohibited this broadcast from being saved:</h2>

          <ul>
            <% @broadcast.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= hidden_field_tag 'page', @current_page %>

    <div id="broadcast-area" class="main-input-area">
      <p>
        <%= f.text_area :content, cols: "100%", rows: "10",
                        title: "Broadcast text goes here", autofocus: 'autofocus' %>
      </p>

      <div id="url-part">
        <%= link_to("Shortens URL",
                    id: "split-arrow",
                    title: "Press this to shorten the URL") %>
        <%= text_field_tag :shorten_url, nil,
                           title: "Enter URL that you wish to shorten",
                           size: "50%" %>

      </div>
      <br/>

      <div id="">
        <%= f.submit 'Broadcast', confirm: 'Do you really want to broadcast?' %> |
        <%= link_to 'Back', broadcasts_path(page: @current_page) %>
      </div>

    </div>

    <div class="sub-input-area">
      <div class="checkboxes">
        <p>
          <%= radio_button_tag 'feeds[alumni_email]', 'cs-alumni', true, title: "Select to broadcast general news" %>
          <%= label_tag 'feeds_alumni_email_alumni', 'General news' %>
        </p>

        <p>
          <%= radio_button_tag 'feeds[alumni_email]', 'cs-alumni-jobs', false, title: "Select to broadcast jobs news" %>
          <%= label_tag 'feeds_alumni_email_alumni-jobs', 'Jobs news' %>
        </p>

        <p>
          <%= check_box_tag 'feeds[email]', '1', true, title: "Select to choose Email feed" %>
          <%= label_tag 'email', 'Email' %>
        </p>

        <p>
          <%= check_box_tag 'feeds[facebook]', '1', true, title: "Select to choose Facebook feed" %>
          <%= label_tag 'facebook', 'Facebook' %>
        </p>

        <p>
          <%= check_box_tag 'feeds[RSS]', '1', true, title: "Select to choose RSS feed" %>
          <%= label_tag 'RSS', 'RSS' %>
        </p>

        <p>
          <%= check_box_tag 'feeds[atom]', '1', true, title: "Select to choose Atom feed" %>
          <%= label_tag 'atom', 'Atom' %>
        </p>

        <p>
          <!--  When TinyMCE was being used. No longer used in example
         onClick: "toogleEditorMode('broadcast-area', 'broadcast[content]', 'twitter-char-count');
                         $('#url-part').toggle();
                         $('#twitter-char-count').toggle();
          -->
          <%= check_box_tag 'feeds[twitter]', '1', true,
                            title: "Select to choose Twitter feed" %>
          <%= label_tag 'twitter', 'Twitter' %>
        </p>

        <%= label_tag 'twitter', '140', id: 'twitter-char-count', title: 'Twitter character remaining count' %>
      </div>
    </div>


<% end %>

csa/app/views/broadcasts/show.html.erb
<h1>Broadcast details</h1>
<p>
  <b>Date broadcast attempted:</b>
  <%= @broadcast.created_at %>
</p>

<p>
  <b>Feeds broadcast to:</b>
  <%= display_feeds @broadcast %>
</p>

<br/><br/>
<p>
  <%= sanitize @broadcast.content %>
</p>

<br/><br/>
<%= link_to 'Back', broadcasts_path(page: @current_page) %>