csa/config/routes.rb
Rails.application.routes.draw do
  resources :users do
    get 'search', on: :collection
  end
  
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
 
  resources :broadcasts, except: [:edit, :update]
  
  # A singleton resource and so no paths requiring ids are generated
  # Also, don't want to support editing of the session
  resource :session, only: [:new, :create, :destroy]
  
  get 'home', to: 'home#index', as: :home
 
  # Will support the following styles of URL:
  # /api/users.json
  # /api/users/1.json
  # /api/users
  namespace :api, defaults: {format: :json} do
    resources :users, except: [:new, :edit]
  end
 
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

csa/app/models/user.rb
class User < ApplicationRecord
  # Include all fields in this or related classes that may be searched
  @@search_columns = ["firstname", "surname", "grad_year", "phone", "email"]
  
  validates_presence_of :firstname, :surname, :grad_year, :email
  validates_numericality_of :grad_year,
                            greater_than_or_equal_to: 1970,
                            less_than_or_equal_to: Time.now.year.to_i
  validates_format_of :email,
                      with: /\A([\w\.\-\+]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
                      message: I18n.t('users.bad-email-format')

  validates_uniqueness_of :email
  
  has_one :image, dependent: :destroy
  has_one :user_detail, dependent: :destroy
  has_many :broadcasts
  
  # This is needed for embedded forms where both the User and UserDetail objects
  # are created at the same time
  accepts_nested_attributes_for :user_detail
  
  def firstname=(value)
    write_attribute :firstname, (value ? value.humanize : nil)
  end

  def surname=(value)
    write_attribute :surname, (value ? value.humanize : nil)
  end

  self.per_page = 6
  
  # Set of helper methods used by users controller

  def self.search_columns
    @@search_columns
  end

  def self.searchable_by(*column_names)
    @@search_columns = []
    [column_names].flatten.each do |name|
      @@search_columns << name
    end
  end

  def search(query, fields=nil, options={})
    with_scope find: {
        conditions: search_conditions(query, fields)} do
      find :all, options
    end
  end

  def self.search_conditions(query, fields=nil)
    return nil if query.blank?
    fields ||= @@search_columns

    # Split the query by commas as well as spaces, just in case
    words = query.split(",").map(&:split).flatten

    binds = {} # Query binding names for substitution to avoid SQL injection!
    or_frags = [] # OR fragments
    count = 1 # To help give bind symbols a unique name
    #cols = columns_hash() # All the column objects
    #puts "columns= #{cols}"

    words.each do |word|
      search_frags = [fields].flatten.map do |field|
        # If a string field then construct a LIKE frag
        # else if a numeric field then look for equality
        #puts "field= #{field}"
        #column = cols[field.to_s]
        #puts "column before = #{column}"
        #unless column.blank?
        #if column.text?
        "LOWER(#{field}) LIKE :word#{count}"
        #elsif column.
        #end
        #end
      end
      or_frags << "(#{search_frags.join(" OR ")})"
      binds["word#{count}".to_sym] = "%#{word.to_s.downcase}%"
      count += 1
    end
    puts "search conditions: #{[or_frags.join(" AND "), binds].to_s}"
    [or_frags.join(" AND "), binds]
  end

end

csa/app/controllers/api/users_controller.rb
class Api::UsersController < Api::ApplicationController
  before_action :set_current_page, except: [:index]
  before_action :set_user, only: [:show, :update, :destroy]
  
  before_action :admin_required, only: [:index, :search, :destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :show_record_not_found

  def search
    # Use will_paginate's :conditions and :joins to search across both the
    # users and user_details tables. search_fields private method will add a field
    # for each checkbox field checked by the user, or returns nil
    # if none were checked. The search_conditions method is defined
    # in lib/searchable.rb and either searches across all columns identified in
    # User.searchable_by or uses the search_fields to constrain the search

    respond_to do |format|
      # Deal with incoming Ajax request for JSON data for autocomplete search field
      format.json {
        @users = User.where(User.search_conditions(params[:q], search_fields(User)))
                      .joins(:user_detail)
                      .order('surname, firstname')
        puts "Users are #{@users.join(' ')}"
      }
    end
  end
  
  # GET /users.json
  # Can be called either by an admin to show any user account or else by
  # a specific user to show their own account, but no one else's
  def index
      @users = User.paginate(page: params[:page],
                             per_page: params[:per_page])
                   .order('surname, firstname')
  end

  # GET /users/1.json
  def show
    if current_user.id == @user.id || is_admin?
      respond_to do |format|
        # If an Ajax request then send back a partial to include just
        # the user's record without layout headers and footers
        format.js { render partial: 'show_local',
                           locals: {user: @user, current_page: @current_page},
                           layout: false }
        format.json # show.json.builder
      end
    else
      indicate_illegal_request I18n.t('users.not-your-account')
    end
  end


  # POST /users.json
  # At the moment we are only allowing the admin user to create new
  # accounts.
  def create
    @user = User.new(user_params)
    
    # Only create a new image if the :image_file parameter
    # was specified
    @image = Image.new(photo: params[:image_file]) if params[:image_file]
    
    # The ImageService model wraps up application logic to
    # handle saving images correctly
    @service = ImageService.new(@user, @image)

    respond_to do |format|
      if @service.save # Will attempt to save user and image
        format.json { render :show, status: :created, location: @user }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1.json
  # Can be called either by an admin to update any user account or else by
  # a specific user to update their own account, but no one else's
  def update
    if current_user.id == @user.id || is_admin?
      @image = @user.image
      @service = ImageService.new(@user, @image)

      respond_to do |format|
        if @service.update_attributes(user_params, params[:image_file])
          format.json { render :show, status: :ok, location: @user }
        else
          format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
    else
      indicate_illegal_request I18n.t('users.not-your-account')
    end
  end

  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def set_current_page
    @current_page = params[:page] || 1
  end
  
  def search_fields(table)
    fields = []
    table.search_columns.each do |column|
      # The parameters have had the table name stripped off so we
      # have to to the same to each search_columns column
      fields << column if params[column.sub(/^.*\./, "")]
    end
    fields = nil unless fields.length > 0
    fields
  end
  
  def indicate_illegal_request(message)
    respond_to do |format|
      format.json {
        render json: "{#{message}}",
               status: :unprocessable_entity
      }
    end
  end

  def show_record_not_found(exception)
    respond_to do |format|
      format.json {
        render json: "{#{I18n.t('users.account-no-exists')}}",
               status: :unprocessable_entity
      }
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:surname, :firstname, :phone, :grad_year, :jobs, :email, user_detail_attributes: [:id, :password, :password_confirmation, :login])
  end
end

csa/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_current_page, except: [:index]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  before_action :admin_required, only: [:index, :search, :destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :show_record_not_found

  def search
    # Use will_paginate's :conditions and :joins to search across both the
    # users and user_details tables. search_fields private method will add a field
    # for each checkbox field checked by the user, or returns nil
    # if none were checked. The search_conditions method is defined
    # in lib/searchable.rb and either searches across all columns identified in
    # User.searchable_by or uses the search_fields to constrain the search

    respond_to do |format|
      format.html {
        @users = User.where(User.search_conditions(params[:q], search_fields(User)))
                     .joins(:user_detail)
                     .paginate(page: params[:page],
                               per_page: params[:per_page])
                     .order('surname, firstname')

        render 'index'
      }
      # Deal with incoming Ajax request for JSON data for autocomplete search field
      format.json {
        @users = User.where(User.search_conditions(params[:q], search_fields(User)))
                      .joins(:user_detail)
                      .order('surname, firstname')
        puts "Users are #{@users.join(' ')}"
      }
    end
  end
  
  # GET /users
  # GET /users.json
  # Can be called either by an admin to show any user account or else by
  # a specific user to show their own account, but no one else's
  def index
      @users = User.paginate(page: params[:page],
                             per_page: params[:per_page])
                   .order('surname, firstname')
  end

  # GET /users/1
  # GET /users/1.json
  def show
    if current_user.id == @user.id || is_admin?
      respond_to do |format|
        # If an Ajax request then send back a partial to include just
        # the user's record without layout headers and footers
        format.js { render partial: 'show_local',
                           locals: {user: @user, current_page: @current_page},
                           layout: false }
        format.html # show.html.erb
        format.json # show.json.builder
      end
    else
      indicate_illegal_request I18n.t('users.not-your-account')
    end
  end

  # GET /users/new
  def new
    @user = User.new
    @user.user_detail = UserDetail.new
  end

  # GET /users/1/edit
  # Can be called either by an admin to edit any user account or else by
  # a specific user to edit their own account, but no one else's
  def edit
    if !(current_user.id == @user.id || is_admin?)
      indicate_illegal_request I18n.t('users.not-your-account')
    end
  end

  # POST /users
  # POST /users.json
  # At the moment we are only allowing the admin user to create new
  # accounts.
  def create
    @user = User.new(user_params)
    
    # Only create a new image if the :image_file parameter
    # was specified
    @image = Image.new(photo: params[:image_file]) if params[:image_file]
    
    # The ImageService model wraps up application logic to
    # handle saving images correctly
    @service = ImageService.new(@user, @image)

    respond_to do |format|
      if @service.save # Will attempt to save user and image
        format.html { redirect_to(user_url(@user, page: @current_page),
                                  notice: I18n.t('users.account-created')) }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  # Can be called either by an admin to update any user account or else by
  # a specific user to update their own account, but no one else's
  def update
    if current_user.id == @user.id || is_admin?
      @image = @user.image
      @service = ImageService.new(@user, @image)

      respond_to do |format|
        if @service.update_attributes(user_params, params[:image_file])
          format.html { redirect_to(user_url(@user, page: @current_page),
                                    notice: I18n.t('users.account-created')) }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
    else
      indicate_illegal_request I18n.t('users.not-your-account')
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url(page: @current_page) }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def set_current_page
    @current_page = params[:page] || 1
  end
  
  def search_fields(table)
    fields = []
    table.search_columns.each do |column|
      # The parameters have had the table name stripped off so we
      # have to to the same to each search_columns column
      fields << column if params[column.sub(/^.*\./, "")]
    end
    fields = nil unless fields.length > 0
    fields
  end
  
  def indicate_illegal_request(message)
    respond_to do |format|
      format.html {
        flash[:error] = message
        redirect_back_or_default(home_url)
      }
      format.json {
        render json: "{#{message}}",
               status: :unprocessable_entity
      }
    end
  end

  def show_record_not_found(exception)
    respond_to do |format|
      format.html {
        redirect_to(users_url(page: @current_page),
                    notice: I18n.t('users.account-no-exists'))
      }
      format.json {
        render json: "{#{I18n.t('users.account-no-exists')}}",
               status: :unprocessable_entity
      }
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:surname, :firstname, :phone, :grad_year, :jobs, :email, user_detail_attributes: [:id, :password, :password_confirmation, :login])
  end
end

csa/app/helpers/users_helper.rb
module UsersHelper
  # We display either the image associated user or if there
  # isn't one we display a default image
  def image_for(user, size = :medium)
    if user.image
      # I wanted to create a clickable link so that the image
      # could be shown full size. To do this we get a URL to an
      # image of the right size, and also create an image_text
      # variable that is used as the HTML title and as
      # alternative text if the image cannot be displayed.
      # user.image.photo.url is the URL to the full size
      # image. Setting the border to "0" removes the border.
      user_image = user.image.photo.url(size)
      image_text = "Image of #{user.firstname} #{user.surname}"
      link_to image_tag(user_image, class: 'image-tag',
                        alt: image_text,
                        title: image_text, border: '0'),
              user.image.photo.url
    else
      # Creates a non-clickable default image
      image_tag("blank-cover_#{size}.png",
                class: 'image-tag', alt: 'No photo available',
                title: 'No photo available', border: '0')
    end
  end
  
  def remote_image_for(user, page, size = :medium)
    if user.image
      link_to_rem user, page, user.image.photo.url(size),
                  "Image of #{user.firstname} #{user.surname}"
    else
      link_to_rem user, page, "blank-cover_#{size}.png", "No photo available"
    end
  end

  def checkbox_search_fields
    result = ""
    count = 1
    User.search_columns.each do |column|
      result += "<p>"
      #result += check_box_tag column.sub!(/^.*\./, ""), "1", false,
      result += check_box_tag column, "1", false,
                              #id: "User#{count}" ,
                              class: "user_search_checkbox",
                              title: "Select to focus search. All blank is same as all selected"
      result += "\n"
      result += label column, column
      result += "</p>"
      count += 1
    end
    result.html_safe
  end

  private

  def link_to_rem(user, page, image_path, text_info)
    link_to image_tag(image_path, alt: text_info,
                      title: text_info, border: "0"),
            user_path(user, page: page),
            class: 'image-tag',
            method: :get,
            remote: true
    #update: id,
    #before: "q_auto_completer.setToBeHidden(false)"
  end


end

csa/app/views/users/_show.html.erb
<p>
  <b><%= I18n.t('email') %>:</b>  <%= user.email %>
</p>
<p>
  <b><%= I18n.t('phone') %>:</b>  <%= user.phone %>
</p>
<p>
  <b><%= I18n.t('grad-year') %>:</b>  <%= user.grad_year %>
</p>
<p>
  <b><%= I18n.t('jobs') %>:</b>  <%= user.jobs %>
</p>

csa/app/views/users/_show_local.html.erb
<div class="content-area">
  <h2><%= user.firstname %>  <%= user.surname %></h2>

  <div class="content-image">
    <%= image_for(user, :large) %>
    <div class="content-links">
      <%= link_to I18n.t('edit'), edit_user_path(user, page: current_page) %> |
      <%= link_to I18n.t('close'), '', rel: 'nofollow', id: 'close-user-detail' %>
    </div>
  </div>

  <div class="content-detail">
    <%= render partial: 'show', locals: {user: user} %>
  </div>
</div>

csa/app/views/users/_users_list.html.erb
<% if users_list.length > 0 %>
    <table class="sortable" id="sortabletable">

      <thead>
      <tr>
        <th class="unsortable"></th>
        <!-- No header for the image -->
        <th><%= I18n.t('surname') %></th>
        <th><%= I18n.t('firstname') %></th>
        <th><%= I18n.t('email') %></th>
        <th><%= I18n.t('grad-year') %></th>
        <th class="unsortable"></th>
        <th class="unsortable"></th>
        <th class="unsortable"></th>
      </tr>
      </thead>
      <tbody>
      <% users_list.each do |user| %>
          <tr>

            <td><%= image_for(user, :medium) %></td>
            <td><%= user.surname %></td>
            <td><%= user.firstname %></td>
            <td><%= user.email %></td>
            <td><%= user.grad_year %></td>
            <td><%= link_to image_tag('eye.jpg', alt: I18n.t('show'),
                                      title: I18n.t('show-details'), border: '0'),
                            user_path(user, page: users_list.current_page),
                            class: 'image-tag',
                            method: :get,
                            remote: true %></td>
            <td><%= link_to image_tag('edit.png', alt: I18n.t('edit'),
                                      title: I18n.t('edit-item'), border: '0'),
                            edit_user_path(user, page: users_list.current_page) %></td>
            <td><%= link_to image_tag('destroy.gif', alt: I18n.t('destroy'),
                                      title: I18n.t('destroy-item'), border: '0'),
                            user_path(user, page: users_list.current_page),
                            data: {confirm: I18n.t('are-you-sure')},
                            method: :delete %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <br/>
<% end %>
<div class="digg_pagination">
  <div>
    <%= page_entries_info users_list %>
  </div>
  <%= will_paginate users_list, container: false %>
</div>

<br/>
<%= link_to 'New User', new_user_path(page: users_list.current_page) %>

csa/app/views/users/edit.html.erb
<div>
  <h1><%= I18n.t('users.editing-account')%></h1>

  <%= form_for(@user, html: {multipart: true }) do |f| %>
      <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

            <ul>
              <% @user.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div>
        <%=  image_for(@user, :large) %> <br /><br />
      </div>

      <div>
        <%= hidden_field_tag 'page', @current_page %>
        <div>
          <b><%= f.label :firstname, I18n.t('firstname') %></b><br />
          <%= f.text_field :firstname, autofocus: 'autofocus' %><br /><br />
        </div>
        <div>
          <b><%= f.label :surname, I18n.t('surname') %></b><br />
          <%= f.text_field :surname %><br /><br />
        </div>
        <div>
          <b><%= f.label :email, I18n.t('email') %></b><br />
          <%= f.email_field :email %><br /><br />
        </div>
        <div>
          <b><%= f.label :phone, I18n.t('phone') %></b><br />
          <%= f.phone_field :phone %><br /><br />
        </div>
        <div>
          <b><%= f.label :grad_year, I18n.t('grad-year') %></b><br />
          <%= f.text_field :grad_year %><br /><br />
        </div>
        <div>
          <b><%= f.label :jobs, I18n.t('jobs') %></b>
          <%= f.check_box :jobs %><br /><br />
        </div>
        <div>
          <b><%= label :user, I18n.t('image') %></b><br />
          <%= file_field_tag :image_file %>
        </div>
        <br />
        <%= f.submit I18n.t('update') %> |
        <%= link_to I18n.t('show'), user_path(@user, page: @current_page) %> |
        <% if is_admin? %>
            <%= link_to I18n.t('back'), users_path(page: @current_page) %>
        <% else %>
            <%= link_to I18n.t('back'), home_path %>
        <% end %>
  <% end %>
  </div>

</div>

csa/app/views/users/index.html.erb
<h1><%=I18n.t('users.accounts')%></h1>

<div class='main-input-area'>
  <%=  render partial: 'users_list', object: @users %>
</div>

<div class='sub-input-area'>
  <%= form_tag search_users_path, title: I18n.t('users.search-accounts'), method: :get do %>
      <div class='checkboxes'>
        <%= checkbox_search_fields %>
      </div>
      <div id='search-submit'>
        <%= submit_tag I18n.t('users.search') %>
        <%= text_field_tag :q,  nil, class: 'ui-autocomplete-input', 
              title: I18n.t('users.search-accounts'), 
              autofocus: 'autofocus',
              autocomplete: 'off' %>
        <img id='surname-spinner' src='/assets/spinner.gif' style='display:none;' alt=<%=I18n.t('please-wait')%>/>
      </div>
  <% end %>

  <div id="user-detail">
  </div>

</div>



 

 


 

csa/app/views/users/new.html.erb
<h1><%= I18n.t('users.sign-up') %></h1>

<% @user.user_detail.password = @user.user_detail.password_confirmation = nil %>

<%= form_for(@user, html: {multipart: true}) do |user_form| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= hidden_field_tag 'page', @current_page %>

    <div>
      <b><%= user_form.label :firstname, I18n.t('firstname') %></b><br/>
      <%= user_form.text_field :firstname, autofocus: 'autofocus' %>
      <br/><br/>
    </div>

    <div>
      <b><%= user_form.label :surname, I18n.t('surname') %></b><br/>
      <%= user_form.text_field :surname %>
      <br/><br/>
    </div>

    <div>
      <b><%= user_form.label :phone, I18n.t('phone') %></b><br/>
      <%= user_form.phone_field :phone %>
      <br/><br/>
    </div>

    <div>
      <b><%= user_form.label :grad_year, I18n.t('grad-year') %></b><br/>
      <%= user_form.text_field :grad_year %>
      <br/><br/>
    </div>

    <div>
      <b><%= user_form.label :jobs, I18n.t('jobs') %></b><br/>
      <%= user_form.check_box :jobs %>
      <br/><br/>
    </div>

    <div>
      <b><%= label :user, I18n.t('image') %></b><br/>
      <%= file_field_tag :image_file %>
      <br/>
    </div>
    <div>
      <b><%= user_form.label :email, I18n.t('email') %></b><br/>
      <%= user_form.email_field :email %>
      <br/><br/>
    </div>
    <%= user_form.fields_for :user_detail do |user_fields| %>
        <div>
          <b><%= user_fields.label :login, I18n.t('sessions.login') %></b><br/>
          <%= user_fields.text_field :login %>
          <br/><br/>
        </div>
        <div>
          <b><%= user_fields.label :password, I18n.t('sessions.password') %></b><br/>
          <%= user_fields.password_field :password %>
          <br/><br/>
        </div>
        <div>
          <b><%= user_fields.label 'password_confirmation', I18n.t('sessions.password-confirm') %></b><br/>
          <%= user_fields.password_field :password_confirmation %>
          <br/><br/>
        </div>
    <% end %>
    <br/>
    <%= user_form.submit I18n.t('create') %> |
    <% if is_admin? %>
        <%= link_to I18n.t('back'), users_path(page: @current_page) %>
    <% else %>
        <%= link_to I18n.t('back'), home_path %>
    <% end %>
<% end %>

csa/app/views/users/show.html.erb
<div>
  <h1><%= @user.firstname %>  <%= @user.surname %></h1>
  <div class='content-image'>
    <%=  image_for(@user, :large) %>
    <div class='content-links'>
      <%= link_to I18n.t('edit'), edit_user_path(@user, page: @current_page)%> |
      <% if is_admin? %>
          <%= link_to I18n.t('back'), users_path(page: @current_page) %>
      <% else %>
          <%= link_to I18n.t('back'), home_path %>
      <% end %>
    </div>
  </div>

  <div class='content-detail'>
    <%=  render partial: 'show', locals: {user: @user} %>
  </div>
</div>